apiVersion: v1
kind: Service
metadata:
  name: genstack
  namespace: aks-istio-system
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: genstack
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000